language: ruby
 rvm:
 - 2.1.0
 cache: -apt -bundler
 env: -DB=postgresql
 script:
 - RAILS_ENV=test bundle exec rake db:migrate --trace
 - bundle exec rake
 before_script:
 - cp config/database.yml.travis config/database.yml
 - psql -c 'create database travis_YOURapp_test;' -U postgres
 deploy:
 provider: heroku
 api_key:
  secure: %_api_key_%
 app:
  dev: dev.YourAppName
